// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/hello/hello.proto

package hello

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType defines the type of message being sent in the stream
type MessageType int32

const (
	MessageType_UNKNOWN               MessageType = 0
	MessageType_HEARTBEAT             MessageType = 1
	MessageType_COMMAND               MessageType = 2
	MessageType_RESULT                MessageType = 3
	MessageType_ACKNOWLEDGMENT        MessageType = 4
	MessageType_TEMPLATE_UPDATE       MessageType = 5
	MessageType_TEMPLATE_SYNC_REQUEST MessageType = 6
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "UNKNOWN",
		1: "HEARTBEAT",
		2: "COMMAND",
		3: "RESULT",
		4: "ACKNOWLEDGMENT",
		5: "TEMPLATE_UPDATE",
		6: "TEMPLATE_SYNC_REQUEST",
	}
	MessageType_value = map[string]int32{
		"UNKNOWN":               0,
		"HEARTBEAT":             1,
		"COMMAND":               2,
		"RESULT":                3,
		"ACKNOWLEDGMENT":        4,
		"TEMPLATE_UPDATE":       5,
		"TEMPLATE_SYNC_REQUEST": 6,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_hello_hello_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_hello_hello_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_hello_hello_proto_rawDescGZIP(), []int{0}
}

// PingRequest is a simple request message for the Ping method
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_hello_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_hello_hello_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// PingResponse is a simple response message from the Ping method
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_hello_hello_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_hello_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_hello_hello_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// CommandRequest contains the command to be executed on the agent
type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_proto_hello_hello_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_hello_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_hello_hello_proto_rawDescGZIP(), []int{2}
}

func (x *CommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

// CommandResponse contains the result of the executed command
type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`                                     // Standard output of the command
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                                       // Error message, if any
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`                // Command exit code
	ExecutionTime int64                  `protobuf:"varint,4,opt,name=execution_time,json=executionTime,proto3" json:"execution_time,omitempty"` // Execution time in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_proto_hello_hello_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_hello_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_hello_hello_proto_rawDescGZIP(), []int{3}
}

func (x *CommandResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *CommandResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandResponse) GetExecutionTime() int64 {
	if x != nil {
		return x.ExecutionTime
	}
	return 0
}

// AgentMessage is sent from the agent to the server
type AgentMessage struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AgentId string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Type    MessageType            `protobuf:"varint,2,opt,name=type,proto3,enum=hello.MessageType" json:"type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_Result
	//	*AgentMessage_SyncRequest
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_proto_hello_hello_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_hello_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_hello_hello_proto_rawDescGZIP(), []int{4}
}

func (x *AgentMessage) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_UNKNOWN
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *HeartbeatMessage {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetResult() *CommandResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *AgentMessage) GetSyncRequest() *TemplateSyncRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_SyncRequest); ok {
			return x.SyncRequest
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Heartbeat struct {
	Heartbeat *HeartbeatMessage `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_Result struct {
	Result *CommandResult `protobuf:"bytes,4,opt,name=result,proto3,oneof"`
}

type AgentMessage_SyncRequest struct {
	SyncRequest *TemplateSyncRequest `protobuf:"bytes,5,opt,name=sync_request,json=syncRequest,proto3,oneof"`
}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_Result) isAgentMessage_Payload() {}

func (*AgentMessage_SyncRequest) isAgentMessage_Payload() {}

// ServerMessage is sent from the server to the agent
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type  MessageType            `protobuf:"varint,2,opt,name=type,proto3,enum=hello.MessageType" json:"type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Command
	//	*ServerMessage_Acknowledgment
	//	*ServerMessage_TemplateUpdate
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_proto_hello_hello_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_hello_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_hello_hello_proto_rawDescGZIP(), []int{5}
}

func (x *ServerMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServerMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_UNKNOWN
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetCommand() *CommandRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *ServerMessage) GetAcknowledgment() *Acknowledgment {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Acknowledgment); ok {
			return x.Acknowledgment
		}
	}
	return nil
}

func (x *ServerMessage) GetTemplateUpdate() *TemplateUpdate {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_TemplateUpdate); ok {
			return x.TemplateUpdate
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Command struct {
	Command *CommandRequest `protobuf:"bytes,3,opt,name=command,proto3,oneof"`
}

type ServerMessage_Acknowledgment struct {
	Acknowledgment *Acknowledgment `protobuf:"bytes,4,opt,name=acknowledgment,proto3,oneof"`
}

type ServerMessage_TemplateUpdate struct {
	TemplateUpdate *TemplateUpdate `protobuf:"bytes,5,opt,name=template_update,json=templateUpdate,proto3,oneof"`
}

func (*ServerMessage_Command) isServerMessage_Payload() {}

func (*ServerMessage_Acknowledgment) isServerMessage_Payload() {}

func (*ServerMessage_TemplateUpdate) isServerMessage_Payload() {}

// HeartbeatMessage contains agent status information
type HeartbeatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CpuUsage      float64                `protobuf:"fixed64,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage   float64                `protobuf:"fixed64,3,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatMessage) Reset() {
	*x = HeartbeatMessage{}
	mi := &file_proto_hello_hello_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatMessage) ProtoMessage() {}

func (x *HeartbeatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_hello_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatMessage.ProtoReflect.Descriptor instead.
func (*HeartbeatMessage) Descriptor() ([]byte, []int) {
	return file_proto_hello_hello_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatMessage) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *HeartbeatMessage) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

// CommandResult contains the result of a command execution
type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ExecutionTime int64                  `protobuf:"varint,5,opt,name=execution_time,json=executionTime,proto3" json:"execution_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_proto_hello_hello_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_hello_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_proto_hello_hello_proto_rawDescGZIP(), []int{7}
}

func (x *CommandResult) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *CommandResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandResult) GetExecutionTime() int64 {
	if x != nil {
		return x.ExecutionTime
	}
	return 0
}

// Acknowledgment is sent to confirm receipt of a command result
type Acknowledgment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Acknowledgment) Reset() {
	*x = Acknowledgment{}
	mi := &file_proto_hello_hello_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acknowledgment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acknowledgment) ProtoMessage() {}

func (x *Acknowledgment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_hello_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acknowledgment.ProtoReflect.Descriptor instead.
func (*Acknowledgment) Descriptor() ([]byte, []int) {
	return file_proto_hello_hello_proto_rawDescGZIP(), []int{8}
}

func (x *Acknowledgment) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Acknowledgment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// TemplateManifest represents the manifest containing all template metadata
type TemplateManifest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Version       string                       `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Updated       int64                        `protobuf:"varint,2,opt,name=updated,proto3" json:"updated,omitempty"` // Timestamp of last manifest update
	Templates     map[string]*TemplateMetadata `protobuf:"bytes,3,rep,name=templates,proto3" json:"templates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Statistics    *TemplateStatistics          `protobuf:"bytes,4,opt,name=statistics,proto3" json:"statistics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateManifest) Reset() {
	*x = TemplateManifest{}
	mi := &file_proto_hello_hello_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateManifest) ProtoMessage() {}

func (x *TemplateManifest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_hello_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateManifest.ProtoReflect.Descriptor instead.
func (*TemplateManifest) Descriptor() ([]byte, []int) {
	return file_proto_hello_hello_proto_rawDescGZIP(), []int{9}
}

func (x *TemplateManifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TemplateManifest) GetUpdated() int64 {
	if x != nil {
		return x.Updated
	}
	return 0
}

func (x *TemplateManifest) GetTemplates() map[string]*TemplateMetadata {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *TemplateManifest) GetStatistics() *TemplateStatistics {
	if x != nil {
		return x.Statistics
	}
	return nil
}

// TemplateMetadata contains metadata for a single template
type TemplateMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Checksum      string                 `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Severity      string                 `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"`
	Platforms     []string               `protobuf:"bytes,6,rep,name=platforms,proto3" json:"platforms,omitempty"`
	DetectionType string                 `protobuf:"bytes,7,opt,name=detection_type,json=detectionType,proto3" json:"detection_type,omitempty"`
	Author        string                 `protobuf:"bytes,8,opt,name=author,proto3" json:"author,omitempty"`
	Created       int64                  `protobuf:"varint,9,opt,name=created,proto3" json:"created,omitempty"`
	Updated       int64                  `protobuf:"varint,10,opt,name=updated,proto3" json:"updated,omitempty"`
	IsCustom      bool                   `protobuf:"varint,11,opt,name=is_custom,json=isCustom,proto3" json:"is_custom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateMetadata) Reset() {
	*x = TemplateMetadata{}
	mi := &file_proto_hello_hello_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateMetadata) ProtoMessage() {}

func (x *TemplateMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_hello_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateMetadata.ProtoReflect.Descriptor instead.
func (*TemplateMetadata) Descriptor() ([]byte, []int) {
	return file_proto_hello_hello_proto_rawDescGZIP(), []int{10}
}

func (x *TemplateMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TemplateMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TemplateMetadata) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *TemplateMetadata) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *TemplateMetadata) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *TemplateMetadata) GetPlatforms() []string {
	if x != nil {
		return x.Platforms
	}
	return nil
}

func (x *TemplateMetadata) GetDetectionType() string {
	if x != nil {
		return x.DetectionType
	}
	return ""
}

func (x *TemplateMetadata) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *TemplateMetadata) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *TemplateMetadata) GetUpdated() int64 {
	if x != nil {
		return x.Updated
	}
	return 0
}

func (x *TemplateMetadata) GetIsCustom() bool {
	if x != nil {
		return x.IsCustom
	}
	return false
}

// TemplateStatistics contains template statistics
type TemplateStatistics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalTemplates    int32                  `protobuf:"varint,1,opt,name=total_templates,json=totalTemplates,proto3" json:"total_templates,omitempty"`
	StandardTemplates int32                  `protobuf:"varint,2,opt,name=standard_templates,json=standardTemplates,proto3" json:"standard_templates,omitempty"`
	CustomTemplates   int32                  `protobuf:"varint,3,opt,name=custom_templates,json=customTemplates,proto3" json:"custom_templates,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TemplateStatistics) Reset() {
	*x = TemplateStatistics{}
	mi := &file_proto_hello_hello_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateStatistics) ProtoMessage() {}

func (x *TemplateStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_hello_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateStatistics.ProtoReflect.Descriptor instead.
func (*TemplateStatistics) Descriptor() ([]byte, []int) {
	return file_proto_hello_hello_proto_rawDescGZIP(), []int{11}
}

func (x *TemplateStatistics) GetTotalTemplates() int32 {
	if x != nil {
		return x.TotalTemplates
	}
	return 0
}

func (x *TemplateStatistics) GetStandardTemplates() int32 {
	if x != nil {
		return x.StandardTemplates
	}
	return 0
}

func (x *TemplateStatistics) GetCustomTemplates() int32 {
	if x != nil {
		return x.CustomTemplates
	}
	return 0
}

// TemplateUpdate is sent from server to agent when a template is updated
type TemplateUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Checksum      string                 `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	IsCustom      bool                   `protobuf:"varint,5,opt,name=is_custom,json=isCustom,proto3" json:"is_custom,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Manifest      *TemplateManifest      `protobuf:"bytes,7,opt,name=manifest,proto3" json:"manifest,omitempty"` // Optional: included as first message in sync
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateUpdate) Reset() {
	*x = TemplateUpdate{}
	mi := &file_proto_hello_hello_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateUpdate) ProtoMessage() {}

func (x *TemplateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_hello_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateUpdate.ProtoReflect.Descriptor instead.
func (*TemplateUpdate) Descriptor() ([]byte, []int) {
	return file_proto_hello_hello_proto_rawDescGZIP(), []int{12}
}

func (x *TemplateUpdate) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *TemplateUpdate) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TemplateUpdate) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *TemplateUpdate) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TemplateUpdate) GetIsCustom() bool {
	if x != nil {
		return x.IsCustom
	}
	return false
}

func (x *TemplateUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TemplateUpdate) GetManifest() *TemplateManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

// TemplateSyncRequest is sent from agent to server to request template sync
type TemplateSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	LastSync      int64                  `protobuf:"varint,2,opt,name=last_sync,json=lastSync,proto3" json:"last_sync,omitempty"` // Timestamp of last successful sync
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateSyncRequest) Reset() {
	*x = TemplateSyncRequest{}
	mi := &file_proto_hello_hello_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateSyncRequest) ProtoMessage() {}

func (x *TemplateSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_hello_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateSyncRequest.ProtoReflect.Descriptor instead.
func (*TemplateSyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_hello_hello_proto_rawDescGZIP(), []int{13}
}

func (x *TemplateSyncRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TemplateSyncRequest) GetLastSync() int64 {
	if x != nil {
		return x.LastSync
	}
	return 0
}

var File_proto_hello_hello_proto protoreflect.FileDescriptor

const file_proto_hello_hello_proto_rawDesc = "" +
	"\n" +
	"\x17proto/hello/hello.proto\x12\x05hello\"(\n" +
	"\vPingRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"F\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"*\n" +
	"\x0eCommandRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\"\x83\x01\n" +
	"\x0fCommandResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12%\n" +
	"\x0eexecution_time\x18\x04 \x01(\x03R\rexecutionTime\"\x86\x02\n" +
	"\fAgentMessage\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.hello.MessageTypeR\x04type\x127\n" +
	"\theartbeat\x18\x03 \x01(\v2\x17.hello.HeartbeatMessageH\x00R\theartbeat\x12.\n" +
	"\x06result\x18\x04 \x01(\v2\x14.hello.CommandResultH\x00R\x06result\x12?\n" +
	"\fsync_request\x18\x05 \x01(\v2\x1a.hello.TemplateSyncRequestH\x00R\vsyncRequestB\t\n" +
	"\apayload\"\x88\x02\n" +
	"\rServerMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.hello.MessageTypeR\x04type\x121\n" +
	"\acommand\x18\x03 \x01(\v2\x15.hello.CommandRequestH\x00R\acommand\x12?\n" +
	"\x0eacknowledgment\x18\x04 \x01(\v2\x15.hello.AcknowledgmentH\x00R\x0eacknowledgment\x12@\n" +
	"\x0ftemplate_update\x18\x05 \x01(\v2\x15.hello.TemplateUpdateH\x00R\x0etemplateUpdateB\t\n" +
	"\apayload\"p\n" +
	"\x10HeartbeatMessage\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x03 \x01(\x01R\vmemoryUsage\"\x9b\x01\n" +
	"\rCommandResult\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12%\n" +
	"\x0eexecution_time\x18\x05 \x01(\x03R\rexecutionTime\"G\n" +
	"\x0eAcknowledgment\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x9e\x02\n" +
	"\x10TemplateManifest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x18\n" +
	"\aupdated\x18\x02 \x01(\x03R\aupdated\x12D\n" +
	"\ttemplates\x18\x03 \x03(\v2&.hello.TemplateManifest.TemplatesEntryR\ttemplates\x129\n" +
	"\n" +
	"statistics\x18\x04 \x01(\v2\x19.hello.TemplateStatisticsR\n" +
	"statistics\x1aU\n" +
	"\x0eTemplatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.hello.TemplateMetadataR\x05value:\x028\x01\"\xb6\x02\n" +
	"\x10TemplateMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\tR\bchecksum\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\x12\x1c\n" +
	"\tplatforms\x18\x06 \x03(\tR\tplatforms\x12%\n" +
	"\x0edetection_type\x18\a \x01(\tR\rdetectionType\x12\x16\n" +
	"\x06author\x18\b \x01(\tR\x06author\x12\x18\n" +
	"\acreated\x18\t \x01(\x03R\acreated\x12\x18\n" +
	"\aupdated\x18\n" +
	" \x01(\x03R\aupdated\x12\x1b\n" +
	"\tis_custom\x18\v \x01(\bR\bisCustom\"\x97\x01\n" +
	"\x12TemplateStatistics\x12'\n" +
	"\x0ftotal_templates\x18\x01 \x01(\x05R\x0etotalTemplates\x12-\n" +
	"\x12standard_templates\x18\x02 \x01(\x05R\x11standardTemplates\x12)\n" +
	"\x10custom_templates\x18\x03 \x01(\x05R\x0fcustomTemplates\"\xf1\x01\n" +
	"\x0eTemplateUpdate\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\tR\bchecksum\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1b\n" +
	"\tis_custom\x18\x05 \x01(\bR\bisCustom\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x123\n" +
	"\bmanifest\x18\a \x01(\v2\x17.hello.TemplateManifestR\bmanifest\"M\n" +
	"\x13TemplateSyncRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tlast_sync\x18\x02 \x01(\x03R\blastSync*\x86\x01\n" +
	"\vMessageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\r\n" +
	"\tHEARTBEAT\x10\x01\x12\v\n" +
	"\aCOMMAND\x10\x02\x12\n" +
	"\n" +
	"\x06RESULT\x10\x03\x12\x12\n" +
	"\x0eACKNOWLEDGMENT\x10\x04\x12\x13\n" +
	"\x0fTEMPLATE_UPDATE\x10\x05\x12\x19\n" +
	"\x15TEMPLATE_SYNC_REQUEST\x10\x062\xc6\x01\n" +
	"\fHelloService\x121\n" +
	"\x04Ping\x12\x12.hello.PingRequest\x1a\x13.hello.PingResponse\"\x00\x12A\n" +
	"\x0eExecuteCommand\x12\x15.hello.CommandRequest\x1a\x16.hello.CommandResponse\"\x00\x12@\n" +
	"\rConnectStream\x12\x13.hello.AgentMessage\x1a\x14.hello.ServerMessage\"\x00(\x010\x01B-Z+github.com/SiriusScan/app-agent/proto/hellob\x06proto3"

var (
	file_proto_hello_hello_proto_rawDescOnce sync.Once
	file_proto_hello_hello_proto_rawDescData []byte
)

func file_proto_hello_hello_proto_rawDescGZIP() []byte {
	file_proto_hello_hello_proto_rawDescOnce.Do(func() {
		file_proto_hello_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hello_hello_proto_rawDesc), len(file_proto_hello_hello_proto_rawDesc)))
	})
	return file_proto_hello_hello_proto_rawDescData
}

var file_proto_hello_hello_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_hello_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_hello_hello_proto_goTypes = []any{
	(MessageType)(0),            // 0: hello.MessageType
	(*PingRequest)(nil),         // 1: hello.PingRequest
	(*PingResponse)(nil),        // 2: hello.PingResponse
	(*CommandRequest)(nil),      // 3: hello.CommandRequest
	(*CommandResponse)(nil),     // 4: hello.CommandResponse
	(*AgentMessage)(nil),        // 5: hello.AgentMessage
	(*ServerMessage)(nil),       // 6: hello.ServerMessage
	(*HeartbeatMessage)(nil),    // 7: hello.HeartbeatMessage
	(*CommandResult)(nil),       // 8: hello.CommandResult
	(*Acknowledgment)(nil),      // 9: hello.Acknowledgment
	(*TemplateManifest)(nil),    // 10: hello.TemplateManifest
	(*TemplateMetadata)(nil),    // 11: hello.TemplateMetadata
	(*TemplateStatistics)(nil),  // 12: hello.TemplateStatistics
	(*TemplateUpdate)(nil),      // 13: hello.TemplateUpdate
	(*TemplateSyncRequest)(nil), // 14: hello.TemplateSyncRequest
	nil,                         // 15: hello.TemplateManifest.TemplatesEntry
}
var file_proto_hello_hello_proto_depIdxs = []int32{
	0,  // 0: hello.AgentMessage.type:type_name -> hello.MessageType
	7,  // 1: hello.AgentMessage.heartbeat:type_name -> hello.HeartbeatMessage
	8,  // 2: hello.AgentMessage.result:type_name -> hello.CommandResult
	14, // 3: hello.AgentMessage.sync_request:type_name -> hello.TemplateSyncRequest
	0,  // 4: hello.ServerMessage.type:type_name -> hello.MessageType
	3,  // 5: hello.ServerMessage.command:type_name -> hello.CommandRequest
	9,  // 6: hello.ServerMessage.acknowledgment:type_name -> hello.Acknowledgment
	13, // 7: hello.ServerMessage.template_update:type_name -> hello.TemplateUpdate
	15, // 8: hello.TemplateManifest.templates:type_name -> hello.TemplateManifest.TemplatesEntry
	12, // 9: hello.TemplateManifest.statistics:type_name -> hello.TemplateStatistics
	10, // 10: hello.TemplateUpdate.manifest:type_name -> hello.TemplateManifest
	11, // 11: hello.TemplateManifest.TemplatesEntry.value:type_name -> hello.TemplateMetadata
	1,  // 12: hello.HelloService.Ping:input_type -> hello.PingRequest
	3,  // 13: hello.HelloService.ExecuteCommand:input_type -> hello.CommandRequest
	5,  // 14: hello.HelloService.ConnectStream:input_type -> hello.AgentMessage
	2,  // 15: hello.HelloService.Ping:output_type -> hello.PingResponse
	4,  // 16: hello.HelloService.ExecuteCommand:output_type -> hello.CommandResponse
	6,  // 17: hello.HelloService.ConnectStream:output_type -> hello.ServerMessage
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_hello_hello_proto_init() }
func file_proto_hello_hello_proto_init() {
	if File_proto_hello_hello_proto != nil {
		return
	}
	file_proto_hello_hello_proto_msgTypes[4].OneofWrappers = []any{
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_Result)(nil),
		(*AgentMessage_SyncRequest)(nil),
	}
	file_proto_hello_hello_proto_msgTypes[5].OneofWrappers = []any{
		(*ServerMessage_Command)(nil),
		(*ServerMessage_Acknowledgment)(nil),
		(*ServerMessage_TemplateUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hello_hello_proto_rawDesc), len(file_proto_hello_hello_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hello_hello_proto_goTypes,
		DependencyIndexes: file_proto_hello_hello_proto_depIdxs,
		EnumInfos:         file_proto_hello_hello_proto_enumTypes,
		MessageInfos:      file_proto_hello_hello_proto_msgTypes,
	}.Build()
	File_proto_hello_hello_proto = out.File
	file_proto_hello_hello_proto_goTypes = nil
	file_proto_hello_hello_proto_depIdxs = nil
}
