// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/hello/hello.proto

package hello

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType defines the type of message being sent in the stream
type MessageType int32

const (
	MessageType_UNKNOWN        MessageType = 0
	MessageType_HEARTBEAT      MessageType = 1
	MessageType_COMMAND        MessageType = 2
	MessageType_RESULT         MessageType = 3
	MessageType_ACKNOWLEDGMENT MessageType = 4
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "UNKNOWN",
		1: "HEARTBEAT",
		2: "COMMAND",
		3: "RESULT",
		4: "ACKNOWLEDGMENT",
	}
	MessageType_value = map[string]int32{
		"UNKNOWN":        0,
		"HEARTBEAT":      1,
		"COMMAND":        2,
		"RESULT":         3,
		"ACKNOWLEDGMENT": 4,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_hello_hello_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_hello_hello_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_hello_hello_proto_rawDescGZIP(), []int{0}
}

// PingRequest is a simple request message for the Ping method
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_hello_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_hello_hello_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// PingResponse is a simple response message from the Ping method
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_hello_hello_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_hello_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_hello_hello_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// CommandRequest contains the command to be executed on the agent
type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_proto_hello_hello_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_hello_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_hello_hello_proto_rawDescGZIP(), []int{2}
}

func (x *CommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

// CommandResponse contains the result of the executed command
type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`                                     // Standard output of the command
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                                       // Error message, if any
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`                // Command exit code
	ExecutionTime int64                  `protobuf:"varint,4,opt,name=execution_time,json=executionTime,proto3" json:"execution_time,omitempty"` // Execution time in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_proto_hello_hello_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_hello_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_hello_hello_proto_rawDescGZIP(), []int{3}
}

func (x *CommandResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *CommandResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandResponse) GetExecutionTime() int64 {
	if x != nil {
		return x.ExecutionTime
	}
	return 0
}

// AgentMessage is sent from the agent to the server
type AgentMessage struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AgentId string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Type    MessageType            `protobuf:"varint,2,opt,name=type,proto3,enum=hello.MessageType" json:"type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_Result
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_proto_hello_hello_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_hello_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_hello_hello_proto_rawDescGZIP(), []int{4}
}

func (x *AgentMessage) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_UNKNOWN
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *HeartbeatMessage {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetResult() *CommandResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Heartbeat struct {
	Heartbeat *HeartbeatMessage `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_Result struct {
	Result *CommandResult `protobuf:"bytes,4,opt,name=result,proto3,oneof"`
}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_Result) isAgentMessage_Payload() {}

// ServerMessage is sent from the server to the agent
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type  MessageType            `protobuf:"varint,2,opt,name=type,proto3,enum=hello.MessageType" json:"type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Command
	//	*ServerMessage_Acknowledgment
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_proto_hello_hello_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_hello_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_hello_hello_proto_rawDescGZIP(), []int{5}
}

func (x *ServerMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServerMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_UNKNOWN
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetCommand() *CommandRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *ServerMessage) GetAcknowledgment() *Acknowledgment {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Acknowledgment); ok {
			return x.Acknowledgment
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Command struct {
	Command *CommandRequest `protobuf:"bytes,3,opt,name=command,proto3,oneof"`
}

type ServerMessage_Acknowledgment struct {
	Acknowledgment *Acknowledgment `protobuf:"bytes,4,opt,name=acknowledgment,proto3,oneof"`
}

func (*ServerMessage_Command) isServerMessage_Payload() {}

func (*ServerMessage_Acknowledgment) isServerMessage_Payload() {}

// HeartbeatMessage contains agent status information
type HeartbeatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CpuUsage      float64                `protobuf:"fixed64,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage   float64                `protobuf:"fixed64,3,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatMessage) Reset() {
	*x = HeartbeatMessage{}
	mi := &file_proto_hello_hello_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatMessage) ProtoMessage() {}

func (x *HeartbeatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_hello_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatMessage.ProtoReflect.Descriptor instead.
func (*HeartbeatMessage) Descriptor() ([]byte, []int) {
	return file_proto_hello_hello_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatMessage) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *HeartbeatMessage) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

// CommandResult contains the result of a command execution
type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ExecutionTime int64                  `protobuf:"varint,5,opt,name=execution_time,json=executionTime,proto3" json:"execution_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_proto_hello_hello_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_hello_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_proto_hello_hello_proto_rawDescGZIP(), []int{7}
}

func (x *CommandResult) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *CommandResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandResult) GetExecutionTime() int64 {
	if x != nil {
		return x.ExecutionTime
	}
	return 0
}

// Acknowledgment is sent to confirm receipt of a command result
type Acknowledgment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Acknowledgment) Reset() {
	*x = Acknowledgment{}
	mi := &file_proto_hello_hello_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acknowledgment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acknowledgment) ProtoMessage() {}

func (x *Acknowledgment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_hello_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acknowledgment.ProtoReflect.Descriptor instead.
func (*Acknowledgment) Descriptor() ([]byte, []int) {
	return file_proto_hello_hello_proto_rawDescGZIP(), []int{8}
}

func (x *Acknowledgment) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Acknowledgment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_hello_hello_proto protoreflect.FileDescriptor

const file_proto_hello_hello_proto_rawDesc = "" +
	"\n" +
	"\x17proto/hello/hello.proto\x12\x05hello\"(\n" +
	"\vPingRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"F\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"*\n" +
	"\x0eCommandRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\"\x83\x01\n" +
	"\x0fCommandResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12%\n" +
	"\x0eexecution_time\x18\x04 \x01(\x03R\rexecutionTime\"\xc5\x01\n" +
	"\fAgentMessage\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.hello.MessageTypeR\x04type\x127\n" +
	"\theartbeat\x18\x03 \x01(\v2\x17.hello.HeartbeatMessageH\x00R\theartbeat\x12.\n" +
	"\x06result\x18\x04 \x01(\v2\x14.hello.CommandResultH\x00R\x06resultB\t\n" +
	"\apayload\"\xc6\x01\n" +
	"\rServerMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.hello.MessageTypeR\x04type\x121\n" +
	"\acommand\x18\x03 \x01(\v2\x15.hello.CommandRequestH\x00R\acommand\x12?\n" +
	"\x0eacknowledgment\x18\x04 \x01(\v2\x15.hello.AcknowledgmentH\x00R\x0eacknowledgmentB\t\n" +
	"\apayload\"p\n" +
	"\x10HeartbeatMessage\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x03 \x01(\x01R\vmemoryUsage\"\x9b\x01\n" +
	"\rCommandResult\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12%\n" +
	"\x0eexecution_time\x18\x05 \x01(\x03R\rexecutionTime\"G\n" +
	"\x0eAcknowledgment\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status*V\n" +
	"\vMessageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\r\n" +
	"\tHEARTBEAT\x10\x01\x12\v\n" +
	"\aCOMMAND\x10\x02\x12\n" +
	"\n" +
	"\x06RESULT\x10\x03\x12\x12\n" +
	"\x0eACKNOWLEDGMENT\x10\x042\xc6\x01\n" +
	"\fHelloService\x121\n" +
	"\x04Ping\x12\x12.hello.PingRequest\x1a\x13.hello.PingResponse\"\x00\x12A\n" +
	"\x0eExecuteCommand\x12\x15.hello.CommandRequest\x1a\x16.hello.CommandResponse\"\x00\x12@\n" +
	"\rConnectStream\x12\x13.hello.AgentMessage\x1a\x14.hello.ServerMessage\"\x00(\x010\x01B-Z+github.com/SiriusScan/app-agent/proto/hellob\x06proto3"

var (
	file_proto_hello_hello_proto_rawDescOnce sync.Once
	file_proto_hello_hello_proto_rawDescData []byte
)

func file_proto_hello_hello_proto_rawDescGZIP() []byte {
	file_proto_hello_hello_proto_rawDescOnce.Do(func() {
		file_proto_hello_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hello_hello_proto_rawDesc), len(file_proto_hello_hello_proto_rawDesc)))
	})
	return file_proto_hello_hello_proto_rawDescData
}

var file_proto_hello_hello_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_hello_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_hello_hello_proto_goTypes = []any{
	(MessageType)(0),         // 0: hello.MessageType
	(*PingRequest)(nil),      // 1: hello.PingRequest
	(*PingResponse)(nil),     // 2: hello.PingResponse
	(*CommandRequest)(nil),   // 3: hello.CommandRequest
	(*CommandResponse)(nil),  // 4: hello.CommandResponse
	(*AgentMessage)(nil),     // 5: hello.AgentMessage
	(*ServerMessage)(nil),    // 6: hello.ServerMessage
	(*HeartbeatMessage)(nil), // 7: hello.HeartbeatMessage
	(*CommandResult)(nil),    // 8: hello.CommandResult
	(*Acknowledgment)(nil),   // 9: hello.Acknowledgment
}
var file_proto_hello_hello_proto_depIdxs = []int32{
	0, // 0: hello.AgentMessage.type:type_name -> hello.MessageType
	7, // 1: hello.AgentMessage.heartbeat:type_name -> hello.HeartbeatMessage
	8, // 2: hello.AgentMessage.result:type_name -> hello.CommandResult
	0, // 3: hello.ServerMessage.type:type_name -> hello.MessageType
	3, // 4: hello.ServerMessage.command:type_name -> hello.CommandRequest
	9, // 5: hello.ServerMessage.acknowledgment:type_name -> hello.Acknowledgment
	1, // 6: hello.HelloService.Ping:input_type -> hello.PingRequest
	3, // 7: hello.HelloService.ExecuteCommand:input_type -> hello.CommandRequest
	5, // 8: hello.HelloService.ConnectStream:input_type -> hello.AgentMessage
	2, // 9: hello.HelloService.Ping:output_type -> hello.PingResponse
	4, // 10: hello.HelloService.ExecuteCommand:output_type -> hello.CommandResponse
	6, // 11: hello.HelloService.ConnectStream:output_type -> hello.ServerMessage
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_hello_hello_proto_init() }
func file_proto_hello_hello_proto_init() {
	if File_proto_hello_hello_proto != nil {
		return
	}
	file_proto_hello_hello_proto_msgTypes[4].OneofWrappers = []any{
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_Result)(nil),
	}
	file_proto_hello_hello_proto_msgTypes[5].OneofWrappers = []any{
		(*ServerMessage_Command)(nil),
		(*ServerMessage_Acknowledgment)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hello_hello_proto_rawDesc), len(file_proto_hello_hello_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hello_hello_proto_goTypes,
		DependencyIndexes: file_proto_hello_hello_proto_depIdxs,
		EnumInfos:         file_proto_hello_hello_proto_enumTypes,
		MessageInfos:      file_proto_hello_hello_proto_msgTypes,
	}.Build()
	File_proto_hello_hello_proto = out.File
	file_proto_hello_hello_proto_goTypes = nil
	file_proto_hello_hello_proto_depIdxs = nil
}
